# -*- coding: utf-8 -*-
"""
This family file was auto-generated by $Id: 6ad7fc3eedd9956aa0dfb16fba938677459c8e69 $
Configuration parameters:
  url = http://www.wikiskripta.eu/index.php/Home
  name = ws

Please do not commit this to the Git repository!
"""

from pywikibot import family

class Family(family.Family):
    def __init__(self):
        family.Family.__init__(self)
        self.name = 'ws'
        self.langs = {
            'cs': 'www.wikiskripta.eu',
        }



    def scriptpath(self, code):
        return {
            'cs': '',
        }[code]

    def version(self, code):
        return {
            'cs': u'1.22.0',
        }[code]


    def protocol(self, code):
        return 'HTTPS'
